CREATE DATABASE IF NOT EXISTS ardhi;
USE ardhi;

CREATE TABLE geo_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    place VARCHAR(255) NOT NULL,
    coordinates JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
